
name: natescherer CI

on:
  push:
    branches:
      - master
      - bugfix/**
      - feature/**
  workflow_dispatch:
  pull_request:
  release:
    types: published

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        shell: [pwsh, powershell]
        exclude:
          - os: ubuntu-latest
            shell: powershell
          - os: macos-latest
            shell: powershell
    steps:
    
      - name: checkout
        uses: actions/checkout@v1

      ## We have to run the Pester tests manually because the `pester-tests-report` Action
      ## actually uses our GitHubActions module internally, and produces a conflict due to
      ## multiple same-named module scripts when the Action tries to run our tests itself
      - name: pester tests manually
        id: pesterTests
        shell: pwsh
        run: |
          $modulesToInstall = @(
            'Pester'
            'functional'
          )
          $modulesToInstall | ForEach-Object {
            if (-not (Get-Module -ListAvailable -All $_)) {
              Write-Output "Module [$_] not found, INSTALLING..."
              Install-Module $_ -Force
            }
          }

          Import-Module Pester
          Import-Module ./GitHubActions

          $test_results_dir = Join-Path $PWD _TMP
          $test_results_path = Join-Path $test_results_dir test-results.nunit.xml
          $result_clixml_path = Join-Path $test_results_dir pester-result.xml

          if (-not (Test-Path $test_results_dir)) {
            mkdir $test_results_dir
          }

          $pesterResult = Invoke-Pester -PassThru -OutputFile $test_results_path -Path tests
          Export-Clixml -InputObject $pesterResult -Path $result_clixml_path

          Set-ActionOutput -Name test_results_path -Value $test_results_path
          Set-ActionOutput -Name result_clixml_path -Value $result_clixml_path

      - name: pester tests report
        uses: zyborg/pester-tests-report@v1.3.0
        with:
          test_results_path: ${{ steps.pesterTests.outputs.test_results_path }}
          result_clixml_path: ${{ steps.pesterTests.outputs.result_clixml_path }}
          report_name: TestResults_${{ runner.os }}_${{ matrix.shell }}
          report_title: PWSH GitHub Action Tools Tests