name: CI
on:
  push:
    branches:
      - main
      - bugfix/**
      - feature/**
  workflow_dispatch:
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        shell: [pwsh, powershell]
        exclude:
          - os: ubuntu-latest
            shell: powershell
          - os: macos-latest
            shell: powershell
    steps:
      - name: Set Variables
        run: |
          "BARE_REPOSITORY=$($env:GITHUB_REPOSITORY.split("/")[1])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Pester Tests
        uses: natescherer/pester-tests-report@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          shell: ${{ matrix.shell }}
          tests_fail_step: true
          report_name: TestResults_${{ runner.os }}_${{ matrix.shell }}
          gist_token: ${{ secrets.PESTER_GIST_TOKEN }}
          gist_name: ${{ env.BARE_REPOSITORY }}_TestResults_${{ runner.os }}_${{ matrix.shell }}.md
          gist_badge_label: ${{ runner.os }} ${{ matrix.shell }}
          coverage_paths: src\private,src\public
          coverage_report_name: CoverageResults_${{ runner.os }}_${{ matrix.shell }}
          coverage_gist: true
          coverage_gist_badge_label: Code Coverage
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
  TestRelease:
    if: github.ref_name != 'main' && github.event_name != 'workflow_dispatch'
    needs: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
      - name: Update PowerShell Metadata
        uses: natescherer/update-powershell-metadata-action@v2
        with:
          path: src
          version: ${{ steps.gitversion.outputs.NuGetVersionV2 }}
          copyright: (c) YYYY Nate Scherer. All rights reserved.
      - name: Publish Module to Cloudsmith
        uses: natescherer/publish-powershell-action@v1
        with:
          token: ${{ secrets.CLOUDSMITH_KEY }}
          target: nuget
          nugetUrl: https://nuget.cloudsmith.io/${{ github.repository }}/v3/index.json
          path: src